<p class="product-attribute">
	 The product was last updated on 
				<?php 

					$OM = \Magento\Framework\App\ObjectManager::getInstance();  
					$registry = $OM->get('\Magento\Framework\Registry'); 
					$currentProduct = $registry->registry('current_product');

					if($currentProduct)
					{

					  $newValueCP = $currentProduct->getResource()->getAttribute('lastupdated')->getFrontend()->getValue($currentProduct);
					  if($newValueCP != null) {
					  	echo $newValueCP;
					  } else {
					  	echo ",sorry, product is out off date!";
					  }
					} 
				?>
</p>






